### ISSUE TITLE
" turns into &quot;

### ISSUE THREAD

**Issue by vargaradu** [mpcarolin/markdown-to-hiccup#2]
The quote sympbol in the markdown text gets converted into `&quot;`. 
Is there any way to get around this?

**Comment by mpcarolin** [comment]
Hi vargaradu, thanks for pointing this out. I will look into it and get back to you.

**Comment by mpcarolin** [comment]
Okay so I looked into it. One of my libraries, [hickory](https://github.com/davidsantiago/hickory) automatically escapes html entities, even in cases where it is not necessary or unwanted in hiccup. It's an open issue to allow clients to configure this: https://github.com/davidsantiago/hickory/issues/25

I will see what I can do in the time being. There were a few possible workarounds mentioned in the thread, so I will play around with these.

**Comment by vargaradu** [comment]
Yes, suspected was a dependency who was generating the escaped html. If I have time, I'll check some of those workarounds as well.

Thanks for looking into this!

**Comment by mpcarolin** [comment]
No problem. If you come up with something and are so inclined to get your hands dirty, feel free to make a pull request :)

**Comment by vargaradu** [comment]
OK I've found a hack (app-side with Reagent). Quite hacky, but it does the job:

```
(defn decode-html [html]
  (let [txt (.createElement js/document "textarea")
        _   (set! txt.innerHTML html)]
    txt.value))

(defn not-empty-html [html]
  (and html
       (not= html "<div></div>")))

(defn replaced-unescaped-html [id]
  (let [element       (js/$ (str "#" id))
        html          (.html element)]
    (when (not-empty-html html) 
          (.replaceWith element (decode-html html)))))

(defn docs-did-mount [id]
  (replaced-unescaped-html id))

(defn docs-did-update [id]
  (replaced-unescaped-html id))

(defn docs-page [filename doc-title]
  (let [id (str "docs-" filename)]
    (r/create-class
     {:component-did-mount  #(docs-did-mount id)
      :component-did-update #(docs-did-update id)
      :display-name id
      :reagent-render #(docs-render filename doc-title id)})))```

It's using Javascript's own mechanism of unescaping HTML.

**Comment by amarjeet000** [comment]
So, I am also facing the same issue :)
I was wondering if folks have any workaround that can be used at this library's functions level.

**Comment by mpcarolin** [comment]
@amarjeet000 @vargaradu 
I had to put this off for awhile but I have a solution coming soon (probably in the next few days).

**Comment by amarjeet000** [comment]
@mpcarolin  
Thanks so much for this fix, works great :) Sorry for the late response.

PS:
I saw this warning during compilation 
`WARNING: Use of undeclared Var cljs.reader/read-string at line 19 resources/public/js/compiled/out/markdown_to_hiccup/core.cljc`
Doesn't create problem for me, but just thought of putting here as info.

**Comment by vargaradu** [comment]
HI @mpcarolin, the update works well, but there a few characters which is still escaped in my documents:
`&#39;`
`&ndash;`

Sorry I didn't mention the other characters before.
Not sure where you could get a list with all of them, tried myself but they were always incomplete.

**Comment by mpcarolin** [comment]
@vargaradu  Thanks for the info. I will patch this tomorrow with **every** escapable character this time.

**Comment by mpcarolin** [comment]
Hey @vargaradu, can you perhaps give me some more information about what you are passing the function and what is returned? The two characters you mentioned map to the apostrophe \' symbol and the – (en dash) symbol, respectively. However I have tried these and several other HTML entities and md->hiccup works as expected:

![image](https://user-images.githubusercontent.com/9517356/49198878-7f18ce00-f352-11e8-87ea-6dc4754a6710.png)

In my fix for 5.0.1, I only explicitly handle the characters >, <, ", and & because those are the only characters that the Hickory library escapes, using [this function here](https://github.com/davidsantiago/quoin/blob/master/src/quoin/text.clj#L4).

I am definitely willing to account for other HTML entities, but I want to zero-in on the issue first.

**Comment by mpcarolin** [comment]
Actually I reproduced it, but only in Clojurescript. I assume that's where you're also using this?

**Comment by mpcarolin** [comment]
Good catch. The version I'm working on now uses some standard decoding utilities (goog.string/unescapeEntities for CLJS, and Apache StringEscapeUtils for CLJ). I think this might make things a little slower but at least it will cover everything.

**Comment by mpcarolin** [comment]
Version 0.6.0 just released, now using those standard libraries for decoding each string. This should also get rid of that annoying warning message you mentioned, @amarjeet000 .

![image](https://user-images.githubusercontent.com/9517356/49347334-a88b6f80-f65a-11e8-8d73-5ff39f71ecb3.png)

**Comment by amarjeet000** [comment]
Working smooth now, thanks much
