### ISSUE TITLE
Handle multiple classes on code blocks

### ISSUE THREAD

**Issue by metasoarous** [mpcarolin/markdown-to-hiccup#3]
First off, thanks for this library!

I see that it's possible to specify a single class for a code block by append it to the tick marks in the markdown, as is possible with GitHub markdown in order to specify language type for formatting. However, while GitHub is fine with you specifying multiple such classes, `markdown-to-hiccup` treats the second class name as though it's part of the content of the code block. Example:

    ```edn vega-lite
    {:data {:values [{:a 1 :b 3} {:a 4 :b 8} {:a 7 :b 5}]}
     :mark "point"
     :encoding {:x {:field "a"} :y {:field "b"}}}
    ```
in markdown-to-hiccup =>

    vega
    {:data {:values [{:a 1 :b 3} {:a 4 :b 8} {:a 7 :b 5}]}
     :mark "point"
     :encoding {:x {:field "a"} :y {:field "b"}}}

While GitHub gives us this:

```edn vega-lite
{:data {:values [{:a 1 :b 3} {:a 4 :b 8} {:a 7 :b 5}]}
 :mark "point"
 :encoding {:x {:field "a"} :y {:field "b"}}}
```

It would be extremely valuable for me as I'm adding some functionality to https://github.com/metasoarous/oz which would make it possible to embed vega/vega-lite visualizations in markdown documents using this syntax. The reason two classes is important is that visualizations might either be json or edn, but I obviously don't want to assume every such chunk of code should be rendered as vega-lite, so I need another class to accomplish that. I could have separate classes like `json-vega-lite` & `edn-vega-lite`, but that is somewhat annoying, and won't lead to good rendering as regular markdown (say on GH).

Are you open to markdown-to-hiccup matching the GitHub behavior with respect to this issue?

Thanks in advance!

**Comment by mpcarolin** [comment]
Thanks for the link! You may have deprecated my library in one comment haha. I will check it out and if it covers all the bases this library does then I will post a note in the readme directing people to commonmark-hiccup.

**Comment by yogthos** [comment]
It doesn't look like commonmark-hiccup is actively maintained though, so might make sense to take it over. :)

**Comment by mpcarolin** [comment]
I may try just that 👍

**Comment by metasoarous** [comment]
Great! Thanks for the feedback!

**Comment by mpcarolin** [comment]
@metasoarous, I saw your PR to clj-markdown. I will update this library’s version of clj-markdown later today to include those changes.

**Comment by metasoarous** [comment]
@mpcarolin Wonderful! Thank you! I don't see a release on Clojars yet, but I noticed you're using `deps.edn`, which should allow you to specify a [git dependency](https://clojure.org/news/2018/01/05/git-deps) pointing to the merge commit in the interim, if you're so inclined. 

Thanks again!

**Comment by mpcarolin** [comment]
@metasoarous 

Okay just deployed it as version 6.1. Thank you for your patience!

**Comment by metasoarous** [comment]
Amazing! Thanks so much!
