### ISSUE TITLE
Explicit declaration of clojure.core/spec.alpha dependency

### ISSUE THREAD

**Issue by metasoarous** [mpcarolin/markdown-to-hiccup#4]
It looks like `markdown-to-hiccup` is taking advantage of `clojure.spec.alpha` without manually declaring the dependency in `project.clj`. This may have been behind a build issue which held us up getting Clojupyter support in Oz (see metasoarous/oz#33). I have found a workaround for this, but it might be a good idea to make this dependency more explicit. Thanks!

**Comment by mpcarolin** [comment]
Thanks for heads up! I will explicitly declare it.

**Comment by metasoarous** [comment]
Wonderful! Thank you.
